language: c
 
dist: trusty
sudo: required

services:
  - mysql
 
compiler:
  - gcc

before_install:
    - export TZ=Asia/Taipei
    - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

script:
  - autoreconf --force --install # for travis
  #- ./configure --enable-optimized --enable-protected --without-postgresql && make && make verify
  - ./configure --enable-optimized --without-postgresql && make
  - make verify

notifications:
  email: false
